package org.example.agent

/**
 * Wraps the text into special tag elements, to incorporate into the final prompt.
 * Helpful, if the prompt part is generated by another LLM and we don't want its parts to
 * be misleading to the agent
 */
fun wrapPromptElement(promptPart: String, tag: String? = null): String {
    val header = "\n\n-----START${tag?.uppercase()?.let { " $it" } ?: ""}-----\n"
    val footer = "\n-----END${tag?.uppercase()?.let { " $it" } ?: ""}-----\n\n"

    return "$header$promptPart$footer"
}