[versions]
kotlin = "2.1.21"
koog = "0.4.1"
grazie = "0.8.11"
code-engine = "1.0.0-beta.128"
ktor = "3.1.3"
dotenv = "6.5.1"
slf4j = "2.0.17"
serialization = "1.9.0"
fasterxml-jackson = "2.19.0"
kotlin-logging = "7.0.3"

[libraries]
koog = { module = "ai.koog:koog-agents", version.ref = "koog" }
grazie-koog-executor = { module = "ai.jetbrains.code.prompt:code-prompt-executor-grazie-koog-jvm", version.ref = "code-engine" }
grazie-ktor = { module = "ai.grazie.client:client-ktor", version.ref = "grazie" }
ktor-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor"}
dotenv = { module = "io.github.cdimascio:dotenv-kotlin", version.ref = "dotenv" }
slf4j = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j"}
kotlin-logging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlin-logging" }
kotlin-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization"}
jackson-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "fasterxml-jackson" }
jackson-yaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version.ref = "fasterxml-jackson" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
